/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBlocks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blocks/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBlock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blocks/{hash}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBlockTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexer/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndexerStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scripts/{script_hash}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScriptHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scripts/{script_hash}/utxos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScriptUtxos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{txid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: string;
            message: string;
            request_id?: string | null;
        };
        BlockDetail: {
            blue_score: string;
            daa_score: string;
            hash: string;
            timestamp: string;
            /** Format: int32 */
            tx_count: number;
        };
        BlockSummary: {
            blue_score: string;
            daa_score: string;
            hash: string;
            timestamp: string;
            /** Format: int32 */
            tx_count: number;
        };
        CoverageRange: {
            coverage_class: string;
            end_daa_score: string;
            end_hash: string;
            range_id: string;
            source: string;
            start_daa_score?: string | null;
            start_hash: string;
        };
        HealthResponse: {
            status: string;
            version: string;
        };
        IndexedContext: {
            indexed_score?: string | null;
            is_synced: boolean;
            network: string;
            source: string;
            virtual_daa_score?: string | null;
        };
        IndexerStatusResponse: {
            coverage?: null | components["schemas"]["CoverageRange"];
            coverage_evaluation: string;
            indexed_block_hash?: string | null;
            indexed_score?: string | null;
            lag_blocks?: string | null;
            lag_daa_score?: string | null;
            /** Format: double */
            last_blocks_per_second?: number | null;
            last_checkpoint_hash?: string | null;
            last_error?: string | null;
            last_error_at?: string | null;
            /** Format: int64 */
            last_indexed_blocks?: number | null;
            /** Format: int64 */
            last_indexed_transactions?: number | null;
            /** Format: int64 */
            last_poll_duration_ms?: number | null;
            last_poll_finished_at?: string | null;
            last_poll_started_at?: string | null;
            last_start_hash?: string | null;
            last_success_at?: string | null;
            /** Format: double */
            last_transactions_per_second?: number | null;
            network: string;
            node_observed_at?: string | null;
            source: string;
            state: string;
            virtual_daa_score?: string | null;
        };
        Page: {
            indexed_context: components["schemas"]["IndexedContext"];
            items: components["schemas"]["BlockSummary"][];
            next_cursor?: string | null;
        };
        ScriptHistoryEvent: {
            amount: string;
            balance_trust_level: string;
            daa_score: string;
            /** Format: int32 */
            event_index: number;
            script_hash: string;
            txid: string;
        };
        ScriptHistoryPage: {
            indexed_context: components["schemas"]["IndexedContext"];
            items: components["schemas"]["ScriptHistoryEvent"][];
            next_cursor?: string | null;
        };
        ScriptUtxo: {
            amount: string;
            balance_trust_level: string;
            created_daa_score: string;
            /** Format: int32 */
            output_index: number;
            script_hash: string;
            txid: string;
        };
        ScriptUtxoPage: {
            indexed_context: components["schemas"]["IndexedContext"];
            items: components["schemas"]["ScriptUtxo"][];
            next_cursor?: string | null;
        };
        SearchResponse: {
            query: string;
            result?: null | components["schemas"]["SearchResult"];
        };
        SearchResult: {
            address: string;
            /** @enum {string} */
            kind: "address";
        } | {
            hash: string;
            /** @enum {string} */
            kind: "block";
        } | {
            /** @enum {string} */
            kind: "transaction";
            txid: string;
        };
        TransactionDetail: {
            accepting_daa_score: string;
            accepting_timestamp: string;
            block_time: string;
            compute_mass: string;
            gas: string;
            inputs: components["schemas"]["TransactionInput"][];
            lock_time: string;
            mass: string;
            outputs: components["schemas"]["TransactionOutput"][];
            /** Format: int64 */
            payload_size: number;
            storage_mass: string;
            subnetwork_id: string;
            /** Format: int32 */
            version: number;
        };
        TransactionInput: {
            /** Format: int32 */
            compute_budget: number;
            /** Format: int32 */
            previous_output_index?: number | null;
            previous_output_resolved: boolean;
            previous_txid?: string | null;
            sequence: string;
            /** Format: int32 */
            sig_op_count: number;
        };
        TransactionOutput: {
            amount: string;
            /** Format: int32 */
            output_index: number;
            script_public_key_address?: string | null;
            script_public_key_type?: string | null;
            /** Format: int32 */
            script_public_key_version: number;
        };
        TransactionPage: {
            indexed_context: components["schemas"]["IndexedContext"];
            items: components["schemas"]["TransactionSummary"][];
            next_cursor?: string | null;
        };
        TransactionSummary: {
            accepting_block_hash?: string | null;
            detail?: null | components["schemas"]["TransactionDetail"];
            detail_available: boolean;
            detail_complete: boolean;
            /** Format: int32 */
            input_count: number;
            /** Format: int32 */
            output_count: number;
            txid: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBlocks: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated block summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Invalid pagination query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 32-byte block hash as hex */
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockDetail"];
                };
            };
            /** @description Invalid hash */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Block not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getBlockTransactions: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description 32-byte block hash as hex */
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block transaction summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            /** @description Invalid hash or cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Block transaction effects not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getIndexerStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indexer status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerStatusResponse"];
                };
            };
        };
    };
    getScriptHistory: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description 32-byte script hash as hex */
                script_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coverage-limited script history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptHistoryPage"];
                };
            };
            /** @description Invalid script hash or cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getScriptUtxos: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description 32-byte script hash as hex */
                script_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coverage-limited script UTXOs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptUtxoPage"];
                };
            };
            /** @description Invalid script hash or cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Invalid search query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 32-byte transaction id as hex */
                txid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionSummary"];
                };
            };
            /** @description Invalid transaction id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Transaction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
